workflows:
  ios-release:
    name: iOS TestFlight
    triggering:
      events:
        - tag
      tag_patterns:
        - pattern: 'v*'
          include: true
    environment:
      flutter: stable
      xcode: latest
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.innovimpactafrica.quickforms
      vars:
        GOOGLE_SERVICE_INFO_PLIST: $GOOGLE_SERVICE_INFO_PLIST  # variable Codemagic
    scripts:
      - name: Get Flutter packages
        script: flutter pub get

      - name: Restore GoogleService-Info.plist  # ← ajouté
        script: |
          echo $GOOGLE_SERVICE_INFO_PLIST | base64 --decode > ios/Runner/GoogleService-Info.plist

      - name: Build iOS
        script: flutter build ios --release --no-codesign

    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true